export const consoleHtml = `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agent API Console</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#e9e7f3;background:#11121a}*{box-sizing:border-box}body{margin:0}main{max-width:960px;margin:auto;padding:48px 24px}header{display:flex;justify-content:space-between;gap:20px;align-items:center}a{color:#bab0ff}h1{font-size:38px;letter-spacing:-1.5px;margin:14px 0}h2{font-size:20px}p{color:#a7a8ba;line-height:1.7}.eyebrow{font-size:11px;letter-spacing:2px;color:#b4a8ff}section{margin:24px 0;padding:26px;border:1px solid #30313e;border-radius:18px;background:#1a1b26}.row{display:flex;align-items:center;gap:12px;flex-wrap:wrap}label{display:block;font-size:13px;color:#c7c6d5;margin:16px 0 8px}input,textarea,select,button{font:inherit}input,textarea,select{width:100%;padding:12px;border:1px solid #414152;border-radius:8px;color:#ededf5;background:#11121b}textarea{min-height:110px;resize:vertical}button{padding:12px 18px;border:0;border-radius:8px;color:#151123;background:#b8a8ff;cursor:pointer}button:disabled{opacity:.5;cursor:wait}.subtle{background:#2c2c3b;color:#d3d1e2}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.7;background:#101118;padding:16px;border-radius:8px}#message{color:#ffd4a7}table{width:100%;border-collapse:collapse;font-size:12px}td,th{text-align:left;padding:12px 5px;border-bottom:1px solid #32323d}td button{padding:7px 10px}.token{font-family:ui-monospace,monospace}#token-result{overflow-wrap:anywhere}small{color:#a7a8ba}form>.row{margin-top:18px}[hidden]{display:none!important}@media(max-width:600px){main{padding:28px 16px}section{padding:20px}h1{font-size:30px}header{align-items:flex-start}td{max-width:130px;overflow-wrap:anywhere}}
</style></head><body><main><header><div><span class="eyebrow">AGENT DELIVERY / HTTP API</span><h1 id="name">에이전트 API 콘솔</h1></div><a href="/">웹 화면 ↗</a></header><p>계정에 로그인해 이 에이전트 전용 토큰을 발급하세요. 외부 프로그램은 브라우저 쿠키 없이 Bearer 토큰으로 호출할 수 있습니다.</p><p id="message" role="status"></p><section id="auth-panel"><h2>앱 계정으로 시작하기</h2><p>Launchpad 로그인과 별도로, 이 생성 앱 안에서 사용하는 계정입니다.</p><form id="auth"><label>이름<input name="name" maxlength="80" autocomplete="name"></label><label>이메일<input name="email" type="email" autocomplete="email" required></label><label>비밀번호<input name="password" type="password" minlength="8" maxlength="256" autocomplete="current-password" required></label><div class="row"><button name="action" value="login">로그인</button><button name="action" value="signup" class="subtle">회원가입</button></div></form></section><div id="workspace" hidden><section><div class="row"><h2 id="account">내 API 토큰</h2><button id="logout" class="subtle">로그아웃</button></div><form id="issue"><label>토큰 이름<input name="name" placeholder="나의 자동화" maxlength="80"></label><label>유효기간<select name="expiresInSeconds"><option value="86400">1일</option><option value="3600">1시간</option><option value="604800">7일</option><option value="2592000">30일</option></select></label><div class="row"><button>토큰 발급</button><a href="/openapi.json" target="_blank" rel="noreferrer">OpenAPI 명세 ↗</a></div></form><div id="token-result" hidden><p>토큰 원문은 발급 시 한 번만 표시됩니다. 이 화면을 닫으면 다시 조회할 수 없습니다.</p><pre id="token-value"></pre><button id="copy-token" class="subtle">토큰 복사</button></div><table><thead><tr><th>이름</th><th>만료</th><th>관리</th></tr></thead><tbody id="tokens"></tbody></table></section><section><span class="eyebrow">TRY YOUR ENDPOINT</span><h2>직접 호출해 보기</h2><p>분석·체크리스트는 로컬 규칙으로 실행합니다. AI 도구는 서버에 설정한 OpenAI API 키와 사용료가 필요합니다.</p><form id="run"><label>API 토큰<input id="run-token" class="token" type="password" autocomplete="off" placeholder="lpa_…" required></label><label>도구<select name="tool"><option value="analyze">analyze · 텍스트 통계</option><option value="checklist">checklist · 체크리스트 변환</option><option value="ai">ai · OpenAI 요청</option></select></label><label>입력<textarea name="input" maxlength="20000" required>회의록 정리하기. 다음 작업 확인하기.</textarea></label><div class="row"><button>API 실행 →</button></div></form><pre id="output" hidden></pre><h2>외부 프로그램 연결</h2><pre id="example"></pre><small>토큰은 agent:run 범위만 제공합니다. 만료되거나 해지한 토큰은 즉시 거부됩니다. Sandbox 미리보기는 임시 실행 환경이므로 상시 운영에는 별도 호스팅이 필요합니다.</small></section></div></main><script type="module" src="/agent-console.js"></script></body></html>`;

export const consoleJs = String.raw`const byId = id => document.getElementById(id);
let issuedToken = '';
async function request(url, options = {}) { const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...options.headers } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || '요청에 실패했습니다.'); return data; }
const message = value => { byId('message').textContent = value; };
function signedOut() { issuedToken = ''; byId('run-token').value = ''; byId('token-value').textContent = ''; byId('token-result').hidden = true; byId('output').textContent = ''; byId('workspace').hidden = true; byId('auth-panel').hidden = false; }
async function refresh() {
 const result = await request('/api/auth/me'); byId('account').textContent = result.user.name + '님의 API 토큰'; byId('auth-panel').hidden = true; byId('workspace').hidden = false;
 const tokens = await request('/api/tokens'); byId('tokens').replaceChildren();
 for (const token of tokens) { const row = document.createElement('tr'); const name = document.createElement('td'); name.textContent = token.name; const expiry = document.createElement('td'); expiry.textContent = new Date(token.expiresAt).toLocaleString(); const action = document.createElement('td'); const button = document.createElement('button'); button.className = 'subtle'; button.textContent = token.revokedAt ? '해지됨' : token.expiresAt <= Date.now() ? '만료됨' : '해지'; button.disabled = Boolean(token.revokedAt) || token.expiresAt <= Date.now(); button.addEventListener('click', async () => { try { await request('/api/tokens/' + token.id, { method:'DELETE' }); await refresh(); message('토큰을 해지했습니다.'); } catch(error) { message(error.message); } }); action.append(button); row.append(name,expiry,action); byId('tokens').append(row); }
}
async function formTask(event, task) { event.preventDefault(); const buttons = [...event.target.querySelectorAll('button')]; buttons.forEach(button => button.disabled = true); message(''); try { await task(Object.fromEntries(new FormData(event.target))); } catch(error) { message(error.message); } finally { buttons.forEach(button => button.disabled = false); } }
byId('auth').addEventListener('submit', event => formTask(event, async fields => { await request('/api/auth/' + (event.submitter?.value || 'login'), { method:'POST', body:JSON.stringify(fields) }); event.target.querySelector('[name=password]').value = ''; await refresh(); }));
byId('logout').addEventListener('click', async () => { try { await request('/api/auth/logout',{method:'POST'}); signedOut(); message('로그아웃했습니다.'); } catch(error) { message(error.message); } });
byId('issue').addEventListener('submit', event => formTask(event, async fields => { const token = await request('/api/tokens', { method:'POST', body:JSON.stringify({...fields,expiresInSeconds:Number(fields.expiresInSeconds)}) }); issuedToken = token.token; byId('token-value').textContent = issuedToken; byId('run-token').value = issuedToken; byId('token-result').hidden = false; await refresh(); }));
byId('copy-token').addEventListener('click', async () => { try { await navigator.clipboard.writeText(issuedToken); message('토큰을 복사했습니다.'); } catch { message('복사할 수 없습니다. 표시된 토큰을 직접 선택해 복사해 주세요.'); } });
byId('run').addEventListener('submit', event => formTask(event, async fields => { byId('output').hidden = true; byId('output').textContent = ''; const result = await request('/v1/agent/run',{ method:'POST', credentials:'omit', headers:{Authorization:'Bearer '+byId('run-token').value.trim()},body:JSON.stringify(fields) }); byId('output').hidden = false; byId('output').textContent = JSON.stringify(result,null,2); }));
byId('example').textContent = 'POST ' + location.origin + '/v1/agent/run\nAuthorization: Bearer YOUR_AGENT_TOKEN\nContent-Type: application/json\n\n' + JSON.stringify({tool:'checklist',input:'첫 작업. 두 번째 작업.'},null,2);
try { const config = await request('/api/config'); byId('name').textContent = config.name + ' API'; document.title = config.name + ' · API Console'; try { await refresh(); } catch { signedOut(); } } catch(error) { message(error.message); }
`;
