import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('fashion sample turns explicit dimensions into a real diagram, estimate and saved brief', async ({page,request},testInfo) => {
  test.setTimeout(90_000);
  const config=await (await request.get('/api/config')).json();
  test.skip(config.mode!=='local','The sample regression uses local templates so it never consumes API or subscription credits. Run with PLAYWRIGHT_PORT=3003.');
  const response=await request.post('/api/projects',{data:{kind:'web-app',prompt:'가방/옷 디자인을 설명해주면 도면을 짜주고 얼마나 재료가 들어갈지 치수도 정확하게 재주고 예상 비용까지 예측해주는 그런 앱 만들고 싶어. 제작해주는 곳 연결까지 해주면 좋고'}});
  expect(response.status()).toBe(202);
  const created=await response.json();
  let preview='';
  await expect.poll(async()=>{const project=await(await request.get('/api/projects/'+created.id)).json();preview=project.previewUrl;return project.status;},{timeout:45_000}).toBe('completed');
  const errors:string[]=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.setViewportSize({width:1440,height:1100});
  await page.goto(preview);
  await expect(page.getByRole('heading',{name:'디자인 브리프',exact:true})).toBeVisible();
  await expect(page.locator('#total-cost')).toHaveText('₩83,000');
  await expect(page.locator('#fabric-meters')).toHaveText('0.9 m');
  await expect(page.locator('#drawing-canvas svg')).toHaveAccessibleName('가방 치수 개념도');
  await page.screenshot({path:testInfo.outputPath('atelier-desktop.png'),fullPage:true});

  await page.locator('#description').fill('네이비 토트백. 가로 40cm, 세로 35cm, 폭 15cm, 손잡이 길이 60cm.');
  await page.getByRole('button',{name:/설명에서 치수 불러오기/}).click();
  await expect(page.getByLabel('가로',{exact:true})).toHaveValue('40');
  await expect(page.getByLabel('세로',{exact:true})).toHaveValue('35');
  await expect(page.getByLabel('깊이',{exact:true})).toHaveValue('15');
  await expect(page.getByRole('button',{name:'잉크 컬러'})).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('#drawing-canvas svg')).toContainText('40 cm');
  await expect(page.locator('#drawing-canvas svg')).toContainText('35 cm');
  await expect(page.locator('#total-cost')).toHaveText('₩86,000');
  await expect(page.locator('#fabric-meters')).toHaveText('1.0 m');
  await page.getByLabel('제작 수량',{exact:true}).fill('2');
  await expect(page.locator('#total-cost')).toHaveText('₩113,000');
  await expect(page.locator('#fabric-meters')).toHaveText('1.4 m');
  await page.getByRole('button',{name:/단가와 공임 수정하기/}).click();
  await page.getByLabel('겉감 단가',{exact:true}).fill('15000');
  await expect(page.locator('#total-cost')).toHaveText('₩117,200');
  await page.getByRole('button',{name:/원단 배치/}).click();
  await expect(page.locator('#drawing-canvas svg')).toContainText('원단 폭 150 cm');
  await expect(page.locator('#drawing-canvas svg')).toContainText('배치 길이 1.16m');

  await page.getByLabel('원단 폭',{exact:true}).fill('37');
  await expect(page.getByRole('heading',{name:'치수를 다시 확인해 주세요'})).toBeVisible();
  await expect(page.getByRole('button',{name:/제작 브리프 다운로드/})).toBeDisabled();
  await expect(page.locator('#total-cost')).toHaveText('—');
  await page.getByLabel('원단 폭',{exact:true}).fill('150');
  await expect(page.getByRole('button',{name:/제작 브리프 다운로드/})).toBeEnabled();

  await page.getByLabel('프로젝트 이름').fill('검증한 네이비 토트백');
  await page.getByRole('button',{name:'저장하기',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:/내 프로젝트/}).click();
  await page.locator('[data-load]').filter({hasText:'검증한 네이비 토트백'}).click();
  await expect(page.getByLabel('프로젝트 이름')).toHaveValue('검증한 네이비 토트백');
  await expect(page.getByLabel('제작 수량',{exact:true})).toHaveValue('2');
  await expect(page.locator('#total-cost')).toHaveText('₩117,200');
  await page.getByLabel('프로젝트 이름').fill('수정한 네이비 토트백');
  await page.getByRole('button',{name:'저장하기',exact:true}).click();

  const briefDownload=page.waitForEvent('download');
  await page.getByRole('button',{name:/제작 브리프 다운로드/}).click();
  const brief=JSON.parse(await readFile((await (await briefDownload).path())!,'utf8'));
  expect(brief.format).toBe('atelier-production-brief-v1');
  expect(brief.design.name).toBe('수정한 네이비 토트백');
  expect(brief.estimate.total).toBe(117200);
  expect(brief.estimate.fabric.purchaseMeters).toBe(1.4);
  expect(brief.limitations.join(' ')).toContain('봉제용 실물 패턴이 아닙니다');
  const svgDownload=page.waitForEvent('download');
  await page.getByRole('button',{name:'현재 도면 SVG 다운로드'}).click();
  const svg=await readFile((await(await svgDownload).path())!,'utf8');
  expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"');
  expect(svg).toContain('40 cm');
  await expect(page.getByRole('link',{name:/제작 업체 찾기/})).toHaveAttribute('href',/search\.naver\.com/);
  await expect(page.getByText('외부 검색 · 제휴·문의 전송 기능 없음')).toBeVisible();

  await page.getByRole('button',{name:'베이식 상의',exact:true}).click();
  await expect(page.locator('#drawing-canvas svg')).toHaveAccessibleName('상의 치수 개념도');
  await expect(page.locator('#parts-list')).toContainText('몸판 바운딩 박스');
  await page.setViewportSize({width:390,height:844});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('atelier-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:/내 프로젝트/}).click();
  await expect(page.locator('[data-load]')).toHaveCount(1);
  await page.getByRole('button',{name:'수정한 네이비 토트백 삭제'}).click();
  await expect(page.getByText('아직 저장한 디자인이 없어요.',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'닫기',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:/내 프로젝트/}).click();
  await expect(page.locator('[data-load]')).toHaveCount(0);
  expect(errors).toEqual([]);
});
